seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: /eagle/MDClimSim/tungnd/physics_sim/

  precision: bf16-mixed

  devices: 1
  num_nodes: 1
  accelerator: gpu
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: true

  min_epochs: 1
  max_epochs: 300
  enable_progress_bar: true

  sync_batchnorm: True
  enable_checkpointing: True
  num_sanity_val_steps: 1

  # debugging
  fast_dev_run: false

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: 'physics_sim'
      save_dir: ${trainer.default_root_dir}/test
      name: test

  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/test/checkpoints"
        monitor: "val/loss" # name of the logged metric which determines when model is improving
        mode: "min"
        save_top_k: 1 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: False
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False

    # - class_path: lightning.pytorch.callbacks.EarlyStopping
    #   init_args:
    #     monitor: "val/loss"
    #     mode: "min"
    #     patience: 10 # how many validation epochs of not improving until training stops
    #     min_delta: 0. # minimum change in the monitored metric needed to qualify as an improvement

    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: lightning.pytorch.callbacks.TQDMProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  variables: [
    "tracer",
    "buoyancy",
    "pressure",
    "concentration",
    "velocity_x",
    "velocity_y",
    "D_xx",
    "D_xy",
    "D_yx",
    "D_yy",
    "E_xx",
    "E_xy",
    "E_yx",
    "E_yy",
    "A",
    "B",
    "C_xx",
    "C_xy",
    "C_yx",
    "C_yy",
    "c_zz",
    "density",
    "energy",
    "momentum_x",
    "momentum_y",
    "pressure_im",
    "pressure_re",
    "speed_of_sound",
    "mask",
  ]
  patcher_type: unet_projector
  max_video_size: null # not needed for unet_projectord patcher
  patch_emb_dim: null # not needed for unet_projector patcher
  patch_emb_nheads: null # not needed for unet_projector patcher
  hidden_dimension: null # not needed for unet_projector patcher
  n_hidden_layers: null # not needed for unet_projector patcher
  hidden_channels: 64
  ch_mults: [1, 2, 4]
  is_attn: [False, False, False]
  mid_attn: False
  n_blocks: 2
  channels: 128
  channels_mult: [2, 4, 4]
  z_channels: 16
  z_factor: 1
  embedding_dim: 6
  levels: [8, 8, 8, 5, 5, 5]
  spatial_compression: 16
  temporal_compression: 8
  num_res_blocks: 2
  patch_size: 4
  patch_method: "haar"
  resolution: 1024
  attn_resolutions: [32]
  dropout: 0.0
  legacy_mode: False
  pretrained_path: /eagle/MDClimSim/tungnd/physics_sim/cosmos_ckpts/Cosmos-1.0-Tokenizer-DV8x16x16/autoencoder_in_3c_out_28c.pt
  loss_type: "mse"
  lr: 5e-4
  beta_1: 0.9
  beta_2: 0.95
  warmup_epochs: 10
  max_epochs: 300
  warmup_start_lr: 1e-8
  eta_min: 1e-8

# ---------------------------- DATA -------------------------------------------
data:
  metadata_dict: {
    "active_matter": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/active_matter",
      "data_resolution": [256, 256],
      "channel_names": ["concentration", "velocity_x", "velocity_y", "D_xx", "D_xy", "D_yx", "D_yy", "E_xx", "E_xy", "E_yx", "E_yy"]
    },
    "shear_flow": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/shear_flow",
      "data_resolution": [256, 512],
      "channel_names": ["tracer", "pressure", "velocity_x", "velocity_y"]
    },
    "rayleigh_benard": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/rayleigh_benard",
      "data_resolution": [512, 128],
      "channel_names": ["buoyancy", "pressure", "velocity_x", "velocity_y"]
    },
    "acoustic_scattering_discontinuous": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/acoustic_scattering_discontinuous",
      "data_resolution": [256, 256],
      "channel_names": ["density", "pressure", "speed_of_sound", "velocity_x", "velocity_y"]
    },
    "acoustic_scattering_inclusions": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/acoustic_scattering_inclusions",
      "data_resolution": [256, 256],
      "channel_names": ["density", "pressure", "speed_of_sound", "velocity_x", "velocity_y"]
    },
    "acoustic_scattering_maze": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/acoustic_scattering_maze",
      "data_resolution": [256, 256],
      "channel_names": ["density", "pressure", "speed_of_sound", "velocity_x", "velocity_y"]
    },
    "euler_multi_quadrants_openBC": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/euler_multi_quadrants_openBC",
      "data_resolution": [512, 512],
      "channel_names": ["energy", "density", "pressure", "momentum_x", "momentum_y"]
    },
    "euler_multi_quadrants_periodicBC": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/euler_multi_quadrants_periodicBC",
      "data_resolution": [512, 512],
      "channel_names": ["energy", "density", "pressure", "momentum_x", "momentum_y"]
    },
    "gray_scott_reaction_diffusion": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/gray_scott_reaction_diffusion",
      "data_resolution": [128, 128],
      "channel_names": ["A", "B"]
    },
    "helmholtz_staircase": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/helmholtz_staircase",
      "data_resolution": [1024, 256],
      "channel_names": ["pressure_re", "pressure_im", "mask"]
    },
    "turbulent_radiative_layer_2D": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/turbulent_radiative_layer_2D",
      "data_resolution": [128, 384],
      "channel_names": ["density", "pressure", "velocity_x", "velocity_y"]
    },
    "viscoelastic_instability": {
      "root_dir": "/eagle/MDClimSim/tungnd/data/the_well/normalized/viscoelastic_instability",
      "data_resolution": [512, 512],
      "channel_names": ["pressure", "c_zz", "velocity_x", "velocity_y", "C_xx", "C_xy", "C_yx", "C_yy"]
    }
  }
  n_frames: 33
  batch_size: 1
  num_workers: 1
  pin_memory: False
