# Project-wide directory path configuration
raw_data_path: '<RAW_DATA_PATH>'
cleaned_data_path: '<CLEANED_DATA_PATH>'
normalized_data_path: '<NORMALIZED_DATA_PATH>'
checkpoint_dir: '<CHECKPOINT_DIR>'
embeddings_dir: '<EMBEDDINGS_DIR>'
results_dir: '<RESULTS_DIR>'
tokenizer_path: '<TOKENIZER_PATH>'
cache_dir: '<CACHE_DIR>' 